### ISSUE TITLE
Error in 'compute' command: Error handling chunk: urllib.error.HTTPError: HTTP Error 413: Request Entity Too Large

### ISSUE THREAD

**Issue by pdrieger** [splunk/deep-learning-toolkit#61]
Reading from a lookup file and running the compute command returns an error:
01-04-2021 16:07:22.970 INFO  DispatchExecutor - END OPEN: Processor=compute

01-04-2021 16:07:22.970 INFO  ReducePhaseExecutor - ReducePhaseExecutor=1 action=PREVIEW

01-04-2021 16:07:22.979 ERROR ChunkedExternProcessor - stderr: begin command handler (chunk_size=3131679)

01-04-2021 16:07:22.979 ERROR ChunkedExternProcessor - stderr: is final chunk from Splunk

01-04-2021 16:07:22.979 ERROR ChunkedExternProcessor - stderr: call execution handler (3131679 bytes of data)

01-04-2021 16:07:22.986 ERROR ChunkedExternProcessor - stderr: sending 3101728 bytes

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr: Traceback (most recent call last):

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/etc/apps/dltk/bin/dltk/core/execution/command.py", line 390, in handle_chunk

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:     result = self.execution.handle(self.buffer, final_chunk_from_splunk)

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/etc/apps/dltk/bin/dltk/runtime/base/base_execution.py", line 82, in handle

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:     response = urllib.request.urlopen(request)

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/lib/python3.7/urllib/request.py", line 222, in urlopen

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:     return opener.open(url, data, timeout)

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/lib/python3.7/urllib/request.py", line 531, in open

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:     response = meth(req, response)

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/lib/python3.7/urllib/request.py", line 641, in http_response

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:     'http', request, response, code, msg, hdrs)

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/lib/python3.7/urllib/request.py", line 569, in error

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:     return self._call_chain(*args)

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/lib/python3.7/urllib/request.py", line 503, in _call_chain

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:     result = func(*args)

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:   File "/opt/splunk/lib/python3.7/urllib/request.py", line 649, in http_error_default

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr:     raise HTTPError(req.full_url, code, msg, hdrs, fp)

01-04-2021 16:07:23.103 ERROR ChunkedExternProcessor - stderr: urllib.error.HTTPError: HTTP Error 413: Request Entity Too Large

01-04-2021 16:07:23.104 ERROR ChunkedExternProcessor - stderr: Error handling chunk: urllib.error.HTTPError: HTTP Error 413: Request Entity Too Large

01-04-2021 16:07:23.104 ERROR ChunkedExternProcessor - stderr: NoneType: None

01-04-2021 16:07:23.105 ERROR ChunkedExternProcessor - Error in 'compute' command: Error handling chunk: urllib.error.HTTPError: HTTP Error 413: Request Entity Too Large

**Comment by pdrieger** [comment]
Based on this [link](https://www.keycdn.com/support/413-request-entity-too-large#:~:text=A%20413%20Request%20Entity%20Too,Request%20Entity%20Too%20Large%20response.): A 413 Request Entity Too Large error occurs **when a request made from a client is too large to be processed by the web server**. If your web server is setting a particular HTTP request size limit, clients may come across a 413 Request Entity Too Large response.

**Comment by pdrieger** [comment]
Resolved. In this case a proxy setup was rejecting the traffic due to its size limitations. Not a bug in DLTK.
